//
// Created by mizu on 2026/6/16.
//

#ifndef NAVIGATION_HOMEWORK_GOENEMYBASEANDATTACK_H
#define NAVIGATION_HOMEWORK_GOENEMYBASEANDATTACK_H


class GoEnemyBaseAndAttack {
};


#endif //NAVIGATION_HOMEWORK_GOENEMYBASEANDATTACK_H