//
// Created by mizu on 2026/6/12.
//

#ifndef NAVIGATION_HOMEWORK_PASSWORDRECEIVEANDSEND_H
#define NAVIGATION_HOMEWORK_PASSWORDRECEIVEANDSEND_H


class PasswordReceiveAndSend {
};


#endif //NAVIGATION_HOMEWORK_PASSWORDRECEIVEANDSEND_H